### ISSUE TITLE
Can't reconcile the advance refund using account_reconcilation _widget.

### ISSUE THREAD

**Issue by hitrosol** [OCA/hr-expense#101]
## Module
The name of the module that has a bug.
[hr_advance_clearing](https://github.com/OCA/hr-expense/tree/14.0/hr_expense_advance_clearing)  combine with [account_reconciliation_widget](https://github.com/OCA/account-reconcile/tree/14.0/account_reconciliation_widget)

## Describe the bug

Can't reconcile the advance refund using account_reconcilation _widget.

## To Reproduce
**Affected versions**: currently i test this in version 14.0

1. Create Advance Payment --> Approve -->  Post Journal Entry --> Register Payment for example : 1,000
2. Click Clear Advance button, create clearing advance report for example : 700 --> Approve --> Post Journal Entry, the remaining advance = 300
3.  Click Return Advance --> Register Payment wizard showed, then create Payment.
4. The remaining advance become zero.
5. Go to Invoicing --> fill the bank statement with incoming amount for 300. 
6. Post the bank statment 
7. Click Reconcile button.
8. Try to validate the reconcilation of 300. 
9. Error appear as follow
![image](https://user-images.githubusercontent.com/5949936/152537669-18e2f9b3-6502-4e41-8206-22e1dbdaa638.png)

**Expected behavior**
User can validate the reconciliation of the return advance

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
I can't try this in Runboat since module account_reconciliation_widget is not available in the hr_advance_clearing

**Comment by hitrosol** [comment]
@kittiu @Saran440 Could you please advice me if I miss something in my setting ?
Actually, I have set the Employee Advance Product chart of account with type Current Asset and Reconcilable.

I guess, I can't reconcile the register payment because the reconciliation process requested type of receivable / payable account.

If I change the Employee Advance Product to Receivable, I can do the bank reconciliation after the register payment.
But, If I request new Advance Payment, the status jump from Posted directly to Paid, without having the Register Payment process.

**Comment by kittiu** [comment]
We never test the two module together as well. But you are right, the reconcile pattern is quite restrictive for receivable / payable only (and this is only happen in Odoo v14, if I remember correctly), while for the advance clearing, we need to setup as Current Asset (and it is current asset).

May be we should draw more idea here, not sure how we should go about.

**Comment by hitrosol** [comment]
I usually use the code of COA to mapping the value in the Financial Report, i.e Balance Sheet. Therefore, functionally it's not really mattter if we put the Employee Advance as Receivable. 

If we put account type of Employee Advance to Receivable, then there would be issue how make sure the steps should go to Register Payment after user post the journal entries. 

Maybe others can give other ideas on this?

**Comment by hitrosol** [comment]
hi @kittiu, I was thinking that we should not put the Employee Advance directly as part of the Register Payment when  user return the Employee Advance.  Employee Advance type's is Current Asset, it's not matched in Payments, which supposed to be Account Receivable or Payable.

But it suppose to create another journal entries by debit the Account Receivable and Credit the Employee Advance. Adding new step by said that all the expense already reported and no more settlement for this particular Employee Advance.
In this stage, hopefully the journal can group many lines of Employee advance to one line Account Receivable. 

After that then Finance Officer can register the payment and then reconcile the payment to Bank Statement, or Finance Officer can directly do the reconciliation between Account Receivable and Bank Suspense Account, without do the register payment. 
I saw your PR in v15, but nor really sure if it can solve this problem as well.

**Comment by kittiu** [comment]
> hi @kittiu, I was thinking that we should not put the Employee Advance directly as part of the Register Payment when user return the Employee Advance. Employee Advance type's is Current Asset, it's not matched in Payments, which supposed to be Account Receivable or Payable.
> 
> But it suppose to create another journal entries by debit the Account Receivable and Credit the Employee Advance. Adding new step by said that all the expense already reported and no more settlement for this particular Employee Advance. In this stage, hopefully the journal can group many lines of Employee advance to one line Account Receivable.
> 
> After that then Finance Officer can register the payment and then reconcile the payment to Bank Statement, or Finance Officer can directly do the reconciliation between Account Receivable and Bank Suspense Account, without do the register payment. I saw your PR in v15, but nor really sure if it can solve this problem as well.

You mean, add more dr/cr lines to move current asset to receivable? Can you give me more example with numbers step by step. I can look into it, and try to apply with v15.

For v14, I don't think I can change much (have to see your proposal first), as I deeply use Advance/Clearing in many use cases and in l10n.

**Comment by hitrosol** [comment]
Hi @kittiu, I realized that, returning the remaining advance doesn't need the **Return Advance** button or the Register Payment process, since the advance holder will directly return the money to the bank via bank transfer so the finance staff will see that amount in the bank statement and do the reconciliation between bank statement line with the Employee Advance account. There will be some needs that finance should give the receipt whenever finance receive the remaining advance, especially if it's returned by cash, not to the bank, but i think those work around will cover the needs.

I wonder, how others work with this issue: Return Advance and reconcile it in the bank statement.

**Comment by hitrosol** [comment]
Hi @kittiu, here is my suggestion so user can do the bank reconcilation for the advance return.

As you can see in the step 4, whenever the user click the Return Button, then system will create additional journal entries, Account Receivable (Db) and Employee Advance (Cr) with Journal Type the same as the Expense Report. Also, Outstanding Receipt (Db) and Account Receivable (Cr) as Payment Journal.  

![gambar](https://user-images.githubusercontent.com/5949936/170836704-811d5f17-41d4-4b5b-a443-acf9180e3db3.png)


Regards,

**Comment by kittiu** [comment]
@hitrosol thanks for your attempt to fix this. I wonder if you think on create payment journal, we could combine all the 4 move lines in the same move?

Note: I will consult with our team to see what they think.

**Comment by Saran440** [comment]
this issue can solved at PR https://github.com/OCA/hr-expense/pull/136
