### ISSUE TITLE
Portuguese Translations

### ISSUE THREAD

**Issue by LFPSGS** [OCA/hr-expense#121]
Hi Team! Quick question, I have translated the hr_expense_advance_clearing to Portuguese (Brazilian) and I would like to ask where should I post the .PO file?

Thanks,

**Comment by Saran440** [comment]
@LFPSGS Hello, You can translate this module 2 ways
1. Manual translate by add new file (.po) in folder i18n (https://github.com/OCA/hr-expense/tree/14.0/hr_expense_advance_clearing/i18n)
Example: https://github.com/OCA/hr-expense/tree/14.0/hr_expense_invoice/i18n
2. Translate by OCA weblate. It will auto translate https://translation.odoo-community.org/projects/hr-expense-14-0/hr-expense-14-0-hr_expense_advance_clearing/
