### ISSUE TITLE
[V14] hr_expense_payment  (question), in expense report to pay form, the outstanding debit (if any) is not shown as it like in normal vendor bill 

### ISSUE THREAD

**Issue by bunhin** [OCA/hr-expense#158]
Let's say the company has an outstanding debit amount to an employee, the employee then creates an expense and expense report (without a previous advance report).

When the expense report is reaching the state of "report to pay",  it is expected the outstanding debit amount to the employee to show up and can be used to pay the expense report with the add button (like it is in the normal vendor bill), is it possible with current state? am I missing something because I do not have the information on outstanding debit in the expense report?

**Comment by Saran440** [comment]
Hello @bunhin,

For standard odoo, when you register payment at expense report.
it will create vendor payment but not link between expense and payment.
you must looking for payment at menu vendor > payments

For module `hr_expense_payment` will help link between payment and expense report.
But you must looking for payment at menu vendor > payments

For module `hr_expense_payment_widget_amount` will help show widget between payment and expense report like a vendor bill. if you need link and button link expense report to payment you can try this module https://github.com/OCA/hr-expense/tree/14.0/hr_expense_payment_widget_amount
