### ISSUE TITLE
hr_expense_invoice : to access to the Refunds

### ISSUE THREAD

**Issue by yboujraf** [OCA/hr-expense#201]
**Is your feature request related to a problem?**

Every month I am receiving my credit card statement.
Each expense is an invoice.
Each statement is linked with a journal.
If I am getting a refund, this refunds is sent back to my credit card.
Then I am expecting to link the "refund" instead of "invoice".

**Describe the solution you'd like**
To access to the Refund AND Invoices items and able to link to an expense

Best Regards
Youssef

**Comment by pedrobaeza** [comment]
Expenses are for real expenses, not a credit card journal, so there's no reason to add refunds on the expenses. Closing due to this.
