### ISSUE TITLE
[FIX][V14][V15] - HR Expense Advance Clearing

### ISSUE THREAD

**Issue by LFPSGS** [OCA/hr-expense#202]
Hi Team! I was testing this module alongside my team and we've noticed a lot of new weird behaviors that makes this module unusable. I've tried in V14 and V15 both local and using runboat and they all behave the same.

## Module

hr_expense_advance_clearing

## Describe the bug

1) When creating an advance, Odoo displays the error "Employee advance product has no payable account" because for some reason, the system is only looking if the product has an account set in the field Expense Account (property_account_expense_id) instead of looking to the account set at the Product Category (property_account_expense_categ_id) as well (which is odoo's default behavior for any product).

2) In V15, expense products have their own menu at the Expense module (hr.expense), however the product used for advances doesn't show up there (It is my understanding that to be shown up there it needs to be marked as can_be_expensed = TRUE) which is no longer possible for users, as this checkbox is now invisible in the Product's menu.

3) When creating expense reports and selecting the advance, users can't add expenses lines. The system makes the user to add the expense lines first and then the advance which doesn't make any sense as the advance is in the form header.

4) Even after going through all of that, once you've submitted your expense, it doesn't clear the amount you've expended. Instead, it posts the full advance value in the journal as if you would have expended it all. Meaning, If I advance $100 and expended only $50, the journal entry from my expense report with an advanced would show $100. Which also causes issues with reports and accounting as the values doesn't match and no report displays remaining values as they're all zeroed.

## To Reproduce
**Affected versions**: V14, V15

1) Account Missing:
1.1) Go to Expenses > My Expenses > Advances > Click on "Create"
1.2) Click "add a line"
1.3) Click on "Create"
1.4)Type any value in the "Total" field
1.5) Click on "Save & Close"
1.6) The error message "Employee advance product has no payable account" is displayed.

2)Product not shown in the Expense Menu:
2.1) Go to Expenses > Configuration > Expenses Product
2.2) The product "Employee Advance" is not shown.

3)Expense Report with advance issue:
3.1) Go to Invoicing > Customers > Products
3.2) Remove any filter
3.3) Search for "Employee Advance"
3.4) In the Accounting tab, set the Expense account "600000 Expenses" and save it.
3.5) Go to Expenses > My Expenses > Advances > Click on "Create"
3.6) Give it a name
3.7) Click "add a line"
3.8) Click on "Create"
3.9)Type $100 in the "Total" field
3.10) Click on "Save & Close"
3.11) Click on "Submitt to Manager"
3.12) Cick on "Approve"
3.13) Click on "Post Journal Entries"
3.14) Click on "Register Payment" and create a payment.
3.15) Click on Expenses > My Expenses > Expenses
3.16) Click on "Create"
3.17) Select the advance you've created in steps 3.6-3.10
3.18) The "add a line" option is no longer available.

4)Remaining Value issue:
4.1) Go to Invoicing > Customers > Products
4.2) Remove any filter
4.3) Search for "Employee Advance"
4.4) In the Accounting tab, set the Expense account "600000 Expenses" and save it.
4.5) Go to Expenses > My Expenses > Advances > Click on "Create"
4.6) Give it a name
4.7) Click "add a line"
4.8) Click on "Create"
4.9)Type $100 in the "Total" field
4.10) Click on "Save & Close"
4.11) Click on "Submitt to Manager"
4.12) Cick on "Approve"
4.13) Click on "Post Journal Entries"
4.14) Click on "Register Payment" and create a payment.
4.15) Go to Expenses > My Expenses to Report
4.16) Click on "Create"
4.17) Select a expense product
4.18) Type $50 in the "Total" field and click "Save"
4.19) Click on "Create Report"
4.20) Select the advance you've created in steps 4.6-4.10
4.21) Click on "Submitt to Manager"
4.22) Click on "Approve"
4.23) Click on "Post Journal Entries"
4.24) Look at the field Advance Remaining (advance_sheet_residual) and the value will be the same as the advance total instead of the actual remaining value of $50.
4.25) Click on Expenses > Advances
4.26) Look for the advance created in steps 4.6-4.10, it will be marked as fully paid instead of partially paid.

**Expected behavior**

1) The system should look to both fields and see which one is filled as it does in all the other modules.

2) The Product should be displayed in the list.

3) The option to add lines should continue to be available for the user to select expense lines or create new ones.

4) The remaining value should be properly set (in this example should display $50) but the correct value would be the advance minus the sum of all expense reports that has that advance selected.

Best Regards,
Luiz Fernando

**Comment by Saran440** [comment]
@LFPSGS

1. The system should look to both fields and see which one is filled as it does in all the other modules.
    - you need add account is `currenct asset` and `allow reconciled` to expense account of product only because it special product
2. The Product should be displayed in the list.
    - Employee Advance is special product use in advance document only (and it default already) why clearing and expense should see it?

3. The option to add lines should continue to be available for the user to select expense lines or create new ones.
    - From case https://github.com/OCA/hr-expense/pull/79
    - For the advance with "Clearing Product" define on the advance line.
On the clearing document of that advance (i.e., click "Clear Advance"), system will default those clearing product lines in the sheet.
But, because, Odoo is using widget="many2many", when default line is set, clicking `Add a line` before saved, will result in error.

4. The remaining value should be properly set (in this example should display $50) but the correct value would be the advance minus the sum of all expense reports that has that advance selected.
    - Reason from (1), expense account of advance product must have `currenct asset` and `allow reconciled`. can you change it and test again
