### ISSUE TITLE
Key error in group accces

### ISSUE THREAD

**Issue by caber** [OCA/hr-expense#237]
https://github.com/OCA/hr-expense/blob/ef75d4c00f9b039c420bc3bcc583fdf37b0d6f7b/hr_expense_invoice/models/hr_expense_sheet.py#L19
fails when not in group
maybe change it in

for sheet in self.filtered(lambda rec: rec.id in res):

**Comment by pedrobaeza** [comment]
For which Odoo version? Have you checked https://github.com/OCA/hr-expense/pull/234?

**Comment by pedrobaeza** [comment]
No answer, so closing.

**Comment by caber** [comment]
Hi, Pedro, how are you doing?
I understand your position, I proposed a one liner patch, which
logic didin't account for a dirty workaround but to a logic and solid
bugfix, if there's 0 amount entries, it doesn't make any sense to try to
create new movements to conciliate those sheets, so they should be filtered
out.

Besides that I've not having time or comprehension to understand fully #234
pr, that's way more complicated and with a much broader reach and
objectives.
Having said that, you're the maintainer and that's your call, but IMHO it
doesn't make any service to the bigger objective to let the ecosystem grow
and welcome newcomers and their contributions, and, in the long run it's
not the way to foster community, and let odoo grow.

Cheers from uruguay,
Luis

**Comment by caber** [comment]
The issue it referenced the commit, which was the last released one in
main, at the time of publication.
And no, I having being able the pr's logic, partly cause it's much broader
reach.
#234 it's a feature PR, my proposal would be merely a minimal bugfix,
different beasts altogether.
Thx for your response, neverthe less.
Cheers from Uruguay

**Comment by pedrobaeza** [comment]
It's better to directly say that is for version Odoo 14. The PR is for version 16, so there's no relation. You can propose a PR doing that one liner patch. I didn't want to discourage you, just to keep things clean if no answer.

**Comment by caber** [comment]
The problem was present in all the releases, as the code didn’t have changed

**Comment by pedrobaeza** [comment]
Well, `res` contains a recordset of `account.move`, so I don't see why `for sheet in self.filtered(lambda rec: rec.id in res):` should be correct, comparing `hr.expense.sheet` with `account.move`. Or am I missing something? Moreover, it would be interesting to have the steps to reproduce the problem.

**Comment by caber** [comment]
res is a dict, which keys are sheets ids, and move ids as values.
If you have some invoiced sheet which invoice has amount 0, it does not
create any move, so res doesn't have the key, so there's  a key error at
res[sheet.id]

**Comment by pedrobaeza** [comment]
OK, understood, although is a very rough case. Having an invoice of 0 amount seems weird. Anyway, please do the PR putting such patch.

**Comment by caber** [comment]
Ok, it's that it would be my first in github.
Besides, I believe that the case could be an error, or maybe it could
happen if a partner received free goods, related to the company.
I'll be doing it later today.
Greets from Uruguay,
Luis

**Comment by pedrobaeza** [comment]
A expense with a linked invoice with free goods? Seems very weird, but indeed the hole is there. Check https://odoo-community.org/resources/code for how to contribute.
