### ISSUE TITLE
HR-EXPENSE [16.0] - hr_expense_journal MIGRATION

### ISSUE THREAD

**Issue by yboujraf** [OCA/hr-expense#246]
Dear @Saran440 

Any idea if this module will be migrated in ODOO [16.0] ?

Best Regards

**Comment by Saran440** [comment]
@yboujraf you can review here https://github.com/OCA/hr-expense/pull/251

**Comment by yboujraf** [comment]
Dear @Saran440 

Can't find the hr_expense_journal for version 16.0.
In the meantime, don't know if version 17.0 is done as well ?

Is it published ?

Best Regards,

**Comment by Saran440** [comment]
@yboujraf for version16 i reopen here #251 you can test and if it worked. please approve by step

![Image](https://github.com/user-attachments/assets/01caca92-aecd-40b4-b4de-85544b4c513b)

**Comment by yboujraf** [comment]
Dear @Saran440 

I approuved the module, don't know when will be merged in branch 16.0?

BR

**Comment by yboujraf** [comment]
Dear @Saran440 

Done — here’s the **same ticket**, wording kept intact, with **“Submit expenses” replaced by “Create Report”** everywhere it appears.

---

Hello Support Team,

We would like to report an issue encountered on Odoo 16.0 CE related to expense reporting when no expenses are explicitly selected.

### Context

We are using the community module **hr_expense_journal**.
In our configuration, expenses may be assigned **different payment journals** (one journal per expense, depending on the payment method).

This setup is also used on several other Odoo instances with the same module version, where the issue does not occur. The difference appears to be the data: on the affected instance, draft expenses use **multiple different journals**.

### Observed behavior

When clicking **“Create Report”** (dashboard action) **without selecting any expense**, Odoo automatically batches all expenses “to submit”.

If those expenses reference **more than one journal**, the following error occurs:

```
ValueError: Expected singleton: account.journal(x, y, z)
```

This happens consistently and blocks the report creation flow.

### Expected behavior

One of the following would be expected:

* A clear user-facing message indicating that expenses with different journals must be reported separately, **or**
* Automatic separation into multiple expense reports (one per journal), **or**
* At minimum, no server-side crash.

### Important clarification

If expenses are **manually selected** in the list view and all selected expenses share the **same journal**, the expense report is created successfully.

The error only occurs when:

* No expenses are selected, and
* Odoo auto-selects multiple draft expenses using different journals.

### Steps to reproduce

1. Create multiple draft expenses.
2. Assign **different payment journals** to these expenses.
3. Go to the Expenses dashboard or list view.
4. Click **“Create Report”** without selecting any expense.
5. Observe the server error (“Expected singleton”).

### Technical note

The traceback shows the issue originates from an override of `_get_default_expense_sheet_values()` where a journal field is accessed as a singleton, although the method is called on a multi-recordset when using the “Create Report” flow.

---

We would appreciate your guidance on the recommended behavior in this scenario and whether a fix or improvement is planned.

Thank you in advance for your support.

Kind regards,
Youssef


> RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/www.xxx.be/odoo/odoo/http.py", line 1848, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/service/model.py", line 152, in retrying
    result = func()
             ^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/http.py", line 1876, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/http.py", line 2080, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/http.py", line 763, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/addons/web/controllers/dataset.py", line 43, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/addons/web/controllers/dataset.py", line 34, in _call_kw
    return call_kw(Model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/api.py", line 484, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/api.py", line 469, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/addons/hr_expense/models/hr_expense.py", line 595, in get_expenses_to_submit
    return expenses.action_submit_expenses()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/addons/hr_expense/models/hr_expense.py", line 598, in action_submit_expenses
    context_vals = self._get_default_expense_sheet_values()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/addons/community/hr_expense_journal/models/hr_expense.py", line 18, in _get_default_expense_sheet_values
    val["bank_journal_id"] = self.payment_type_id.id
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/www.xxx.be/odoo/odoo/fields.py", line 5113, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: account.journal(19, 25, 23)

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://www.xxx.be/web/assets/9431-905e4c5/web.assets_backend.min.js:1003:163)
        at XMLHttpRequest.<anonymous> (https://www.xxx.be/web/assets/9431-905e4c5/web.assets_backend.min.js:1011:13)
