### ISSUE TITLE
[14.0] hr_expense_advance_clearing, need code review for "return advance" process.

### ISSUE THREAD

**Issue by kittiu** [OCA/hr-expense#44]
There is a part of code that is nor correctly written.

https://github.com/OCA/hr-expense/blob/14.0/hr_expense_advance_clearing/wizard/account_payment_register.py#L34-L39

It is trying to avoid a warning on default_get() by update account type back and forth.

**Comment by kittiu** [comment]
cc @Saran440 @newtratip

**Comment by kittiu** [comment]
@Saran440 can you fix this please?

**Comment by Saran440** [comment]
Fixed.
