### ISSUE TITLE
[RFC] Does it make sense to have more than one advance-type product?

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/hr-expense#91]
https://github.com/OCA/hr-expense/blob/61a264c61dd626c9e772f5b0eee309ff69caa6d2/hr_expense_advance_clearing/models/hr_expense.py#L33

I have a scenario in which the company contracts a volume of X credits to be used to pay for meals made on trips. This credit is distributed monthly to a specific employee and if any of these credits are left over, the company only supplements the balance in the following month

Example:
*$300 in food credit was transferred to the employee
*$150 was consumed

Total $150

* Next month the company transfers another $150 to the employee.

New balance $300

Now, talking about the possibility of registering other products that can be used as an advance, it is because this process mentioned above seems to suit the purpose of the hr_expense_advance_clearing module well, but it would be important to be able to separate what is a merely financial advance from an advance of credits (including also the separation of the G/L account used). Therefore, one possibility would be to refactor this module to take into account a Boolean that determines if that product is of the advance type or not.

Makes sense ?

**Comment by kittiu** [comment]
The intention of Advance document is to be cleared out. They are acting as transaction document which has ending life.

From the requirement you mentioned, do you mean something similar to petty cash? Where a pot of amount is setup. And then, we consume amount from this pot with expense. Then, when the amount is low, we add amount to the pot up to its max level.
https://github.com/OCA/hr-expense/tree/13.0/hr_expense_petty_cash

**Comment by marcelsavegnago** [comment]
@kittiu thanks for your help
