### ISSUE TITLE
Two Lines Employee Advance skip the Payment Process

### ISSUE THREAD

**Issue by hitrosol** [OCA/hr-expense#92]
I try in runbot to put the 2 lines of Employee Advance. Sometimes, there will be use case where the employee have to take employee Advance using different AA in one go.
After the manager approved, then the Accounting will Post the Journal
![image](https://user-images.githubusercontent.com/5949936/144975926-a21b5d17-7be6-4b5e-a952-3f98e95a4721.png)

But after the Accounting post the journal, the document directly goes to Paid Status, where it suppposed to Register Payment first.
![image](https://user-images.githubusercontent.com/5949936/144976187-707291ac-cc83-423a-a3fc-9e0d3b82b7df.png)

Is it in purpose ?
@kittiu, i think you will use the analytic account in Employee Advance in the Budget Module, and there is a possibility to have 2 AA as budget source for 1  Employee Advance Report, right ?

Thanks

**Comment by kittiu** [comment]
Yes, it should be able to use multiple AA.

I think your problem is on how accounting is configured.
Can you ensure that Expense Account of Employee Advance (product.product), is set to Current Asset and Reconcilable ?

Can you try that for me?

**Comment by hitrosol** [comment]
Hi @kittiu, I have set the Employee Advance to Current Asset and Reconcilable.
![image](https://user-images.githubusercontent.com/5949936/146232317-0477fd79-4fdc-440a-8fd0-05d040e932b3.png)

![image](https://user-images.githubusercontent.com/5949936/146232650-70fbc30f-3c0d-4804-afb1-2afd42179043.png)

I also have tried this on runbot:
http://3520481-14-0-ee3895.runbot1-2.odoo-community.org/web?debug=1#id=5&action=307&model=hr.expense.sheet&view_type=form&cids=&menu_id=186

![image](https://user-images.githubusercontent.com/5949936/146233232-0076dc55-bf3e-4e18-a6ef-c6ce18898060.png)

I tried the Employee Advance payment for 1 line employee advance, the process is working well.

Regards

**Comment by kittiu** [comment]
Oh, OK. For this problem, I did found it is the bug from Odoo hr_expense module and I already propose the fix there.
https://github.com/odoo/odoo/pull/79227

But I don't think it will be taken care by Odoo now. You may need to make a patch yourself for now.
